### ISSUE TITLE
Know a Current User's Id

### ISSUE THREAD

**Issue by loganwright** [TTFM-Labs/boring-infrastructure#363]
In messages, the `from` field is assigned, and it's not clear which messages are coming from the current user without a reliable way to access this

Because threading conditions aren't as predictable as on JS, the iOS client's messages may be out of order and we can't rely on this

The proposed solution in slack was to add a flag on messages identifying if a message is sent from the current connection so that a user's messages can be identified.

A note on connection generated IDs:
if the id is being generated per connection, that kind of disconnects from the accounts we already have setup for the users through their logins
so if they leave and rejoin a room, they'll appear as a different user to others which could be a problem. I think long term being able to somehow identify who is sending the messages would be ideal

Proposed Solution:

On connection, we include the standard `Authorization: Bearer <#TOKEN#>`  header we use with the backend to authenticate that user and associate messages with their account/id

**Comment by kowalski** [comment]
@bobobob22 lets add userId to all events where we currently have userPeerId. On web part as well. This userId would be the one from users service
